name: .NET Core Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  guard-admin-labels:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'Зачтено'

    steps:
      - name: Check User Permission
        id: check_permission
        uses: sushichop/action-repository-permission@v1
        with:
          required-permission: admin

      - name: Remove Label and Comment
        # Если has-permission == false, значит метку повесил студент
        if: steps.check_permission.outputs.has-permission == 'false'
        uses: actions/github-script@v7
        with:
          script: |
            const labelToRemove = 'Accepted';
            const user = context.actor;

            await github.rest.issues.removeLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              name: labelToRemove
            });

            // 2. Оставляем предупреждение
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: `⚠️ @${user}, вы не можете самостоятельно помечать работу как принятую. Вас запомнили`
            });
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Run Filtered Tests
        shell: bash
        run: |
          # Если это PR, берем метки. Если это push в main, запускаем всё.

          if [ "${{ github.event_name }}" == "pull_request" ]; then
            LABELS='${{ toJson(github.event.pull_request.labels.*.name) }}'
          else
            LABELS="NONE"
          fi
          if [[ $LABELS == *"Зачтено"* ]]; then 
              echo "Work accepted, no need to re-run full test suite if not needed."
              # Можно либо выйти, либо просто проигнорировать эту метку в FILTER
          fi

          FILTER=""

          if [[ $LABELS == "NONE" ]]; then
            echo "Push detected. No running tests"
            exit 0
          fi

          if echo "$LABELS" | grep -q "BST-lab";   then FILTER+="TestCategory=BST|"; fi
          if echo "$LABELS" | grep -q "AVL-lab";   then FILTER+="TestCategory=AVL|"; fi
          if echo "$LABELS" | grep -q "RB-lab";    then FILTER+="TestCategory=RB|"; fi
          if echo "$LABELS" | grep -q "SPLAY-lab"; then FILTER+="TestCategory=Splay|"; fi
          if echo "$LABELS" | grep -q "TREAP-lab"; then FILTER+="TestCategory=Treap|"; fi

          FILTER=${FILTER%|}

          if [ -z "$FILTER" ]; then
            echo "No lab labels found. Running nothing."
            exit 0
          else
            echo "Running tests for filter: $FILTER"
            dotnet test --no-build --filter "$FILTER"
          fi
